### ISSUE TITLE
DF website: add non-UK options to list of countries

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#145]
When using the shopping cart on the DF website, you are asked to fill in a country as part of your address, but the dropdown only gives one option: United Kingdom. We need to provide options for overseas members as well.

The form is at:
https://www.dipterists.org.uk/checkout/485/order_information

Under "Subscription":

![image](https://user-images.githubusercontent.com/16039111/94248774-d4a26f80-ff16-11ea-9f8a-b07a05d2b98f.png)

I've had a look through the commerce settings for the website but I can't see anywhere that lets me adjust this dropdown.

**Comment by BirenRathod** [comment]
@kitenetter I just logged in as you and checked the above subscription page and found there is no restriction of selecting other countries.

**Comment by kitenetter** [comment]
The only options I get are "United Kingdom" or "none". This is also the case for other users - this issue has arisen because someone in Ireland wishes to join Dipterists Forum, and there is no appropriate country for them to select.

**Comment by kitenetter** [comment]
See Biren's screenshot in #131 

I get a different view (using Firefox):

![image](https://user-images.githubusercontent.com/16039111/94253306-061e3980-ff1d-11ea-8735-60a4766c5146.png)

**Comment by BirenRathod** [comment]
Can you send me the URL please? browser is not a problem.

**Comment by BirenRathod** [comment]
Which user have logged in with?

**Comment by BirenRathod** [comment]
Can you send me Ireland's username or name?

**Comment by BirenRathod** [comment]
@kitenetter Can you see now? There will be two buttons appear. So I guess for order no 485, you need to add new member if not you can select existing one.

**Comment by kitenetter** [comment]
@BirenRathod I'm not seeing any change. This is the sequence:
1. I'm currently logged out of the DF website
2. I go to the "Join DF" page (https://www.dipterists.org.uk/index.php/join)
3. I go to "Membership of Dipterists Forum" and click on "Add to cart"
4. I then go to "your cart" (https://www.dipterists.org.uk/index.php/cart) and click on the "Checkout" button, and the use the "Continue as Guest" option (which is what any new member will need to do)
5. That takes me to the "Order information" page - for this order it is https://www.dipterists.org.uk/index.php/checkout/609/order_information
6. The "Country" dropdown list on that page only has one option, United Kingdom, as before:

![image](https://user-images.githubusercontent.com/16039111/94261303-8ba7e680-ff29-11ea-994f-64e7ca49b4c6.png)

**Comment by BirenRathod** [comment]
@kitenetter I implemented that now so you see all country list.

**Comment by kitenetter** [comment]
Excellent, thanks Biren. Closing.

**Comment by kitenetter** [comment]
Still getting complaints about the handling of non-UK addresses:
"when I logged in, the website allowed me to enter Ireland, but then would not accept the postcode, and included United Kingdom in my address"

Are we able to change things to allow non-UK addresses to be entered?

**Comment by BirenRathod** [comment]
@kitenetter 
I made some changes and updates today. Can you check if that is working? I masquerade as you and it shows all countries when I tried to add address from "My account" link.  So right way to do is if people can add address first from their account then they don't need to add again while placing a order. that way they should able to add country of their choice.

**Comment by BirenRathod** [comment]
@kitenetter Although I have mentioned above about adding address first in their account. That is only possible for registered user, so ignore that bit because that don't work for anonymous users. I have implemented the form now, so this will work now.
