### ISSUE TITLE
DF website home page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#57]
Uploaded images have a tick box to specify if they should appear on the Home page, but this tick box is not controlling the behaviour correctly: the image of the Banded General (the one that is the wrong format for the home page) does not have the box ticked, but is still appearing on the home page.

At the moment the home page image behaviour seems to be:
- The same image appears each time you go to the home page; the image then changes if you stay on the home page for long enough

I would prefer:
- One of the home page images is displayed at random each time you visit or refresh the home page, but the image does not then change while you stay on the page

The image captions seem too large - can we reduce the font a little, add a drop shadow to the font, and use abbreviations for the CC licence (i.e. "CC BY-SA" rather than "Creative Commons Attribution-ShareAlike"). Or alternatively use the graphic version of the CC licence.

Reminder to add a full-screen option to the video playback.

**Comment by BirenRathod** [comment]
- Front image filter has been added which has removed the Banded General image. 
- Image order has been implemented to random. So displays in no particular order.
- Text size has been reduced now but text shadow settings setup by module, so left as it is. 
- Abbreviations added for all licence type.

Note: Remind me to add full-screen option to the video before going live date.

**Comment by kitenetter** [comment]
- For the events block, can we display date as well as event name, and also location if it can be fitted in without looking too congested
- On the right-hand side there is a link to "Join us" that currently points to http://dipterists.org.uk/joining-dipterists-forum - it needs editing to point to http://dipterists.org.uk/join
- Add links to allow people to follow DF on Twitter and Facebook (@kitenetter to check which Facebook link is correct)
- Page footer needs updating, see separate issue

**Comment by BirenRathod** [comment]
Sorted.

**Comment by BirenRathod** [comment]
@kitenetter 
- Full screen option for video have been resolved.
- After unticked the box for the front page, save the page and clear cache. There is a maximum chance of appearing image after unticked front page box option. because it loads from the cache, so clearing the cache is important.

**Comment by kitenetter** [comment]
One more request from the DF committee: they noted that at first glance the top of the home page does not make it clear that it is the Dipterists Forum website (the logo and name only appears at the bottom).

We will in due need to remove the "Important notice" text. Can we use that space to add some sort of banner, using the logo and the text similar to the old site:

![image](https://user-images.githubusercontent.com/16039111/47855551-d2900e80-dddc-11e8-8cf2-141aa4ffcf66.png)

The text is:
The Society for the study of flies (Diptera)
Affiliated to the British Entomological and Natural History Society (BENHS)
[URL link for BENHS: http://www.benhs.org.uk/]

I'm not sure whether this banner would be best above the menus bar or below - probably above?

**Comment by kitenetter** [comment]
The video display here is a great improvement on what we had before:
https://www.dipterists.org.uk/media/1

However, it still doesn't allow the video to be expanded to full screen (nor does it show the video's duration, or allow you to move to a different part of the video, or adjust the volume settings). If that's not possible, can we add a short piece of text to the above page (above or below the video itself) to give people the link to view the original video on vimeo?

**Comment by BirenRathod** [comment]
@kitenetter 

I have added the site logo on the website and removed the important notice now.

**Comment by kitenetter** [comment]
Thanks Biren. I think the banner is only needed on the home page. And I should have made it clearer that it doesn't need to look _exactly_ like the old site. If possible I'd suggest:
- Using a black and white version of the logo
- Moving the text so that the strip is wider and less deep
- Only displaying it on the home page

Something like this?:

![image](https://user-images.githubusercontent.com/16039111/48058195-c1187f00-e1ad-11e8-87d1-e8cc4dc02c19.png)

**Comment by BirenRathod** [comment]
Yes, that is a good idea and that give me more flexibility in terms of manipulating the display.

**Comment by BirenRathod** [comment]
@kitenetter 
- The logo has been implemented. it is now in black and white format.
- Text move to the right
- logo only appears on the front page.

**Comment by kitenetter** [comment]
Removing from the high priority milestone, as the video enhancement can be done later.
